export type { PublicRoutesType } from './PublicRoutes'
export type { PrivateRoutesType } from './PrivateRouts'
export type { NavigationProps } from './PrivateRouts'
export { default as PublicRoutes } from './PublicRoutes'
export { default as PrivateRoutes } from './PrivateRouts'
export { default as BottomTab } from './BottomTab'
